/**
 * In-browser pick entry. Loads data/budget.json (one entry per eligible playoff
 * player with seed + cost). Validates roster against budget cap. Outputs a JSON
 * blob the entrant downloads / copies for the admin.
 */
const PicksUI = (() => {
  let budget = null;       // { players: [...], generated_at, ... }
  let config = null;
  let bySeed = {};         // seed -> [players sorted by cost desc]
  let selected = {};       // seed -> player_id
  let entrantName = '';
  let entrantEmail = '';   // optional
  let tiebreaker = '';     // predicted highest single-game points by one of my picks

  function effectiveCost(cost) {
    return Math.max(cost, config.budget / 16);
  }

  async function open(_config) {
    config = _config;
    const ui = document.getElementById('picks-ui');
    ui.innerHTML = '<div style="color:var(--text-muted)">Loading eligible players…</div>';
    try {
      budget = await fetch('data/budget.json?t=' + Date.now()).then(r => {
        if (!r.ok) throw new Error('budget.json missing — admin must run scripts/fetch_budget.py');
        return r.json();
      });
    } catch (e) {
      ui.innerHTML = `<div style="color:var(--over-budget)">${e.message}</div>
        <p style="margin-top:1rem;color:var(--text-secondary);font-size:.85rem">
        Player pool is generated by the admin after the play-in finalizes seeds. Check back soon.</p>`;
      return;
    }
    // Group by seed
    bySeed = {};
    for (const p of budget.players || []) {
      (bySeed[p.seed] ||= []).push(p);
    }
    for (const s of Object.keys(bySeed)) {
      bySeed[s].sort((a, b) => b.cost - a.cost);
    }

    // Restore from localStorage
    const saved = JSON.parse(localStorage.getItem('nbaFantasyPicks') || '{}');
    entrantName = saved.name || '';
    entrantEmail = saved.email || '';
    selected = saved.picks || {};
    tiebreaker = saved.tiebreaker || '';

    render();
  }

  function render() {
    const ui = document.getElementById('picks-ui');
    const cap = config.budget;
    let html = `<label>Your name<input id="picks-name" type="text" value="${entrantName.replace(/"/g, '&quot;')}"></label>`;
    html += `<label style="margin-top:.4rem">Email (optional — for payout contact)<input id="picks-email" type="email" value="${entrantEmail.replace(/"/g, '&quot;')}" placeholder="you@example.com"></label>`;
    html += `<div style="margin-top:.6rem;font-size:.8rem;color:var(--text-secondary)">Budget cap: <strong>${cap.toFixed(2)}</strong> · minimum cost per pick: <strong>${(cap / 16).toFixed(2)}</strong></div>`;

    html += '<div style="margin-top:1rem">';
    for (let s = 1; s <= 8; s++) {
      const players = bySeed[s] || [];
      const sel = selected[s] || '';
      let opts = `<option value="">— pick a ${s}-seed —</option>`;
      for (const p of players) {
        const eff = effectiveCost(p.cost);
        const label = `${p.name} (${p.team}) — PPG ${p.cost.toFixed(1)}${eff > p.cost ? ` → ${eff.toFixed(2)}` : ''}`;
        opts += `<option value="${p.player_id}" ${sel === p.player_id ? 'selected' : ''}>${label}</option>`;
      }
      html += `<div class="seed-row"><div class="seed-label">${s} seed <span style="font-size:.7em;color:var(--text-muted)">scores ×${(1 + s / 10).toFixed(1)}</span></div>`;
      html += `<select data-seed="${s}">${opts}</select>`;
      const chosen = players.find(p => p.player_id === sel);
      const cost = chosen ? effectiveCost(chosen.cost).toFixed(2) : '—';
      html += `<div class="pick-cost" id="cost-${s}">$${cost}</div></div>`;
    }
    html += '</div>';

    html += '<div id="picks-budget-bar"><span>Total spent</span><span id="picks-spent">$0.00 / $' + cap.toFixed(2) + '</span></div>';

    html += `<div style="margin-top:1rem;padding-top:.75rem;border-top:1px solid var(--border)">
      <label style="display:block">Tiebreaker — predicted highest single-game points scored by any of your 8 picks, across the entire playoffs
        <input id="picks-tiebreaker" type="number" min="0" max="150" step="1" value="${tiebreaker}" placeholder="e.g. 50">
      </label>
    </div>`;

    html += '<div id="picks-warnings"></div>';
    html += `<div id="picks-actions">
      <button id="picks-submit">Submit picks</button>
      <button id="picks-clear" class="secondary">Clear</button>
    </div>`;
    html += '<div id="picks-status" class="picks-status"></div>';
    ui.innerHTML = html;

    document.getElementById('picks-name').addEventListener('input', e => {
      entrantName = e.target.value;
      persist();
    });

    document.getElementById('picks-email').addEventListener('input', e => {
      entrantEmail = e.target.value;
      persist();
    });

    document.getElementById('picks-tiebreaker').addEventListener('input', e => {
      tiebreaker = e.target.value;
      persist();
      recompute();
    });

    ui.querySelectorAll('select[data-seed]').forEach(sel => {
      sel.addEventListener('change', () => {
        const s = sel.dataset.seed;
        selected[s] = sel.value;
        const chosen = (bySeed[s] || []).find(p => p.player_id === sel.value);
        document.getElementById(`cost-${s}`).textContent = chosen ? `$${effectiveCost(chosen.cost).toFixed(2)}` : '—';
        persist();
        recompute();
      });
    });

    document.getElementById('picks-submit').addEventListener('click', submit);
    document.getElementById('picks-clear').addEventListener('click', clear);

    recompute();
  }

  function persist() {
    localStorage.setItem('nbaFantasyPicks', JSON.stringify({ name: entrantName, email: entrantEmail, picks: selected, tiebreaker }));
  }

  function recompute() {
    let spent = 0;
    const seen = new Set();
    const dupes = [];
    for (let s = 1; s <= 8; s++) {
      const pid = selected[s];
      if (!pid) continue;
      const p = (bySeed[s] || []).find(x => x.player_id === pid);
      if (!p) continue;
      if (seen.has(pid)) dupes.push(p.name);
      seen.add(pid);
      spent += effectiveCost(p.cost);
    }
    const cap = config.budget;
    const bar = document.getElementById('picks-budget-bar');
    document.getElementById('picks-spent').textContent = `$${spent.toFixed(2)} / $${cap.toFixed(2)}`;
    bar.classList.toggle('over', spent > cap + 1e-9);
    const warn = document.getElementById('picks-warnings');
    const msgs = [];
    if (spent > cap + 1e-9) msgs.push(`Over budget by $${(spent - cap).toFixed(2)}`);
    if (dupes.length) msgs.push(`Duplicate player(s): ${dupes.join(', ')}`);
    const tb = parseFloat(tiebreaker);
    if (!tiebreaker || isNaN(tb) || tb < 0) msgs.push('Enter a tiebreaker guess');
    warn.textContent = msgs.join(' · ');
    document.getElementById('picks-submit').disabled = !!msgs.length || !entrantName.trim();
  }

  async function submit() {
    if (!entrantName.trim()) return;
    const picks = {};
    for (let s = 1; s <= 8; s++) {
      const pid = selected[s];
      if (!pid) return;
      const p = (bySeed[s] || []).find(x => x.player_id === pid);
      if (!p) return;
      picks[String(s)] = {
        player_id: p.player_id,
        name: p.name,
        team: p.team,
        seed: s,
        cost: p.cost,
        effective_cost: effectiveCost(p.cost),
      };
    }
    const blob = {
      name: entrantName.trim(),
      email: entrantEmail.trim() || null,
      submitted_at: new Date().toISOString(),
      tiebreaker: parseFloat(tiebreaker),
      picks,
    };

    const status = document.getElementById('picks-status');
    const btn = document.getElementById('picks-submit');
    const endpoint = config.picks_endpoint || '';

    if (!endpoint) {
      // Fallback: download a JSON file (admin endpoint not configured yet)
      const dl = new Blob([JSON.stringify(blob, null, 2)], { type: 'application/json' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(dl);
      a.download = `picks_${entrantName.trim().replace(/\W+/g, '_')}.json`;
      a.click();
      status.className = 'picks-status warn';
      status.textContent = 'Submission endpoint not configured yet — downloaded a JSON file you can send to the commissioner.';
      return;
    }

    btn.disabled = true;
    status.className = 'picks-status';
    status.textContent = 'Sending…';
    try {
      // Apps Script CORS quirk: send as text/plain to avoid preflight
      await fetch(endpoint, {
        method: 'POST',
        mode: 'no-cors',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' },
        body: JSON.stringify(blob),
      });
      // no-cors → opaque response; assume success unless it threw
      status.className = 'picks-status ok';
      status.innerHTML = `✓ Submitted! Your picks for <strong>${entrantName}</strong> were sent. You can close this window.`;
    } catch (err) {
      status.className = 'picks-status err';
      status.textContent = 'Submission failed: ' + err.message;
    } finally {
      btn.disabled = false;
    }
  }

  function clear() {
    selected = {};
    persist();
    render();
  }

  return { open };
})();
